version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "protein-hub-backend-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-115e8symkxezq"
s3_prefix = "protein-hub-backend-dev"
region = "ap-southeast-2"
profile = "personal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
