AWSTemplateFormatVersion: 2010-09-09
Description: >-
  protein-hub-backend
Transform:
- AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: TokenAuthorizer
        Authorizers:
          TokenAuthorizer:
            FunctionArn: !GetAtt TokenAuthorizerFunction.Arn

  TokenAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/authorizer/handler.handler
      Runtime: nodejs14.x

  getRecipeByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/getRecipeById/handler.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 100
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RecipeTable
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET

  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: recipes-prod
      AttributeDefinitions:
        -
          AttributeName: "pk"
          AttributeType: "S"
        -
          AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "pk"
          KeyType: "HASH"
        -
          AttributeName: "sk"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
